include:
  - local: 'pipeline-includes/templates.yml'
  - local: 'pipeline-includes/common_dirs.yml'

stages:
  - init
  - build
  - deploy
  - misc

init_send_docker_script:
  stage: init
  script:
    - cp "${CI_PROJECT_DIR}/init_docker_install.sh" "${DEPLOY_PATH}/init_docker_install.sh"
    - chmod +x "${DEPLOY_PATH}/init_docker_install.sh"
    - echo "Execution command"
    - echo "sudo ${DEPLOY_PATH}/init_docker_install.sh"
  rules:
    - when: manual

deploy_nginx:
  extends: .compose_deploy_template
  variables:
    COMPOSE_FILE: "compose-nginx.yaml"

deploy_portainer:
  extends: .compose_deploy_template
  variables:
    COMPOSE_FILE: "compose-portainer.yaml"

deploy_registry:
  extends: .compose_deploy_template
  variables:
    COMPOSE_FILE: "compose-registry.yaml"

reload_nginx_conf:
  stage: misc
  script:
    - docker exec "nginx" nginx -s reload
  rules:
    - when: manual
