include:
  - local: 'pipeline-includes/templates.yml'
  - local: 'pipeline-includes/variables.yml'
  - local: 'pipeline-includes/trigger_projects.yml'

stages:
  - init
  - build
  - deploy
  - misc

init_send_docker_script:
  stage: init
  needs: []
  tags:
    - shell
  script:
    - mkdir -p ${COMPOSE_PATH}
    - mkdir -p ${DATA_PATH}
    - cp "${CI_PROJECT_DIR}/init_docker_install.sh" "${DESKTOP_PATH}/init_docker_install.sh"
    - chmod +x "${DESKTOP_PATH}/init_docker_install.sh"
    - echo "Execution command"
    - echo "sudo ${DESKTOP_PATH}/init_docker_install.sh"
  rules:
    - when: manual

deploy_nginx:
  extends: .compose_deploy_template
  needs: []
  before_script:
    - mkdir -p ${SSL_PATH}
    - mkdir -p ${SITES_PATH}
  variables:
    COMPOSE_FILE: "compose-nginx.yaml"

deploy_portainer:
  extends: .compose_deploy_template
  needs: []
  variables:
    COMPOSE_FILE: "compose-portainer.yaml"
  after_script:
    - |
      cat << EOF > ${DESKTOP_PATH}/Portainer.desktop
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Portainer
      Exec=xdg-open https://localhost:9443
      Icon=edit-copy
      Terminal=false
      EOF
      chmod +x ${DESKTOP_PATH}/Portainer.desktop
  rules:
    - when: manual

deploy_registry:
  extends: .compose_deploy_template
  needs: []
  variables:
    COMPOSE_FILE: "compose-registry.yaml"
  after_script:
    - |
      cat << EOF > ${DESKTOP_PATH}/Registry-UI.desktop
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Registry-UI
      Exec=xdg-open https://localhost:9444
      Icon=edit-copy
      Terminal=false
      EOF
      chmod +x ${DESKTOP_PATH}/Registry-UI.desktop
  rules:
    - when: manual

reload_nginx_conf:
  stage: misc
  needs: []
  script:
    - docker kill --signal=HUP nginx
  rules:
    - when: manual
