services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${USER_EMAIL}
      - RENEWAL_INTERVAL=27d
    networks:
      - shared_net
    volumes:
      - shared_static:/var/www/static:ro
      - ${SITES_PATH}:/etc/nginx/user_conf.d:ro
      - ${SSL_PATH}:/etc/letsencrypt
      - /dev/null:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  shared_net:
    name: shared_net

volumes:
  shared_static:
    name: shared_static